services:

  server:
    build:
      context: ./
      dockerfile: server/Dockerfile
    networks:
      - local-network
    ports:
      - "12345:12345"
    environment:
      WS_HOST: "0.0.0.0"
      WS_PORT: 12345
      LOGLEVEL: "INFO"

  client-simple:
    build:
      context: ./
      dockerfile: client_simple/Dockerfile
    networks:
      - local-network
    environment:
      WS_HOST: "server"
      WS_PORT: 12345
      LOGLEVEL: "INFO"
    depends_on:
      - server

networks:
  local-network:
    driver: bridge
