services:

  server:
    profiles: [ 'synchro', 'asyncio', 'multiprocess' ]
    build:
      context: ./
      dockerfile: server/Dockerfile
    networks:
      - local-network
    ports:
      - "12345:12345"
    environment:
      WS_PORT: 12345
      LOGLEVEL: "INFO"
      SERVER_PERIOD: 1
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:12345/healthcheck" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  client-synchro:
    profiles: [ 'synchro' ]
    build:
      context: ./
      dockerfile: client_synchro/Dockerfile
    networks:
      - local-network
    environment:
      WS_HOST: "server"
      WS_PORT: 12345
      LOGLEVEL: "INFO"
    depends_on:
      server:
        condition: service_healthy

  client-asyncio:
    profiles: [ 'asyncio' ]
    build:
      context: ./
      dockerfile: client_asyncio/Dockerfile
    networks:
      - local-network
    environment:
      WS_HOST: "server"
      WS_PORT: 12345
      LOGLEVEL: "INFO"
      LISTENER_PERIOD: 4
      CONSUMER_PERIOD: 1
    depends_on:
      server:
        condition: service_healthy

  client-multiprocess-listener:
    profiles: [ 'multiprocess' ]
    build:
      context: ./
      dockerfile: client_multiprocess/listener/Dockerfile
    networks:
      - local-network
    environment:
      WS_HOST: "server"
      WS_PORT: 12345
      LOGLEVEL: "INFO"
      LISTENER_PERIOD: 4
      CONSUMER_PERIOD: 1
      BROKER_HOST: "rabbitmq"
    depends_on:
      server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    profiles: [ 'multiprocess' ]
    image: rabbitmq:4
    networks:
      - local-network
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  local-network:
    driver: bridge
