services:

  server:
    profiles: [ 'synchro', 'cooperative' ]
    build:
      context: ./
      dockerfile: server/Dockerfile
    networks:
      - local-network
    ports:
      - "12345:12345"
    environment:
      WS_PORT: 12345
      LOGLEVEL: "INFO"
      SERVER_FREQUENCY: 0.5
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:12345/healthcheck" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  client-synchro:
    profiles: [ 'synchro' ]
    build:
      context: ./
      dockerfile: client_synchro/Dockerfile
    networks:
      - local-network
    environment:
      WS_HOST: "server"
      WS_PORT: 12345
      LOGLEVEL: "INFO"
    depends_on:
      server:
        condition: service_healthy

  client-cooperative:
    profiles: [ 'cooperative' ]
    build:
      context: ./
      dockerfile: client_cooperative/Dockerfile
    networks:
      - local-network
    environment:
      WS_HOST: "server"
      WS_PORT: 12345
      LOGLEVEL: "INFO"
    depends_on:
      server:
        condition: service_healthy

networks:
  local-network:
    driver: bridge
